precision: 32
max_epochs: 30
num_nodes: 1
gpus: 0
sync_batchnorm: False
default_root_dir: ${exp_dir}
num_sanity_val_steps: 0
accumulate_grad_batches: 1
gradient_clip_val: 5.0
replace_sampler_ddp: False
resume_from_checkpoint:
